In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import scipy
import sklearn
import spacy
import matplotlib.pyplot as plt
import seaborn as sns
import re
from nltk.corpus import gutenberg, stopwords
from collections import Counter
import timeit

c:\program files\python37\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Pool size changed, may indicate binary incompatibility. Expected 48 from C header, got 64 from PyObject
  return f(*args, **kwds)
c:\program files\python37\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Address size changed, may indicate binary incompatibility. Expected 24 from C header, got 40 from PyObject
  return f(*args, **kwds)


In [2]:
start=timeit.default_timer()

import nltk
nltk.download('popular')

stop=timeit.default_timer()
time=stop-start
print("time runing:",time)

[nltk_data] Downloading collection 'popular'
[nltk_data]    | 
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     C:\Users\KH\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     C:\Users\KH\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     C:\Users\KH\AppData\Roaming\nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     C:\Users\KH\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     C:\Users\KH\AppData\Roaming\nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     C:\Users

In [3]:
start=timeit.default_timer()

# Utility function for standard text cleaning.
def text_cleaner(text):
    # Visual inspection identifies a form of punctuation spaCy does not
    # recognize: the double dash '--'.  Better get rid of it now!
    text = re.sub(r'--',' ',text)
    text = re.sub("[\[].*?[\]]", "", text)
    text = ' '.join(text.split())
    return text
    
# Load and clean the data.
caesar = gutenberg.raw('shakespeare-caesar.txt')
alice = gutenberg.raw('carroll-alice.txt')

# The Chapter indicator is idiosyncratic
caesar = re.sub(r'Chapter \d+', '', caesar)
alice = re.sub(r'CHAPTER .*', '', alice)
    
caesar = text_cleaner(caesar)
alice = text_cleaner(alice)


stop=timeit.default_timer()
time=stop-start
print("time runing:",time)

time runing: 0.020731728000000338


In [4]:
start=timeit.default_timer()

# Parse the cleaned novels. This can take a bit.
nlp = spacy.load('en')

stop=timeit.default_timer()
time=stop-start
print("time runing:",time)

c:\program files\python37\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Pool size changed, may indicate binary incompatibility. Expected 48 from C header, got 64 from PyObject
  return f(*args, **kwds)
c:\program files\python37\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Address size changed, may indicate binary incompatibility. Expected 24 from C header, got 40 from PyObject
  return f(*args, **kwds)


time runing: 0.9750856269999995


In [5]:
start=timeit.default_timer()

# Parse the cleaned novels. This can take a bit.
caesar_doc = nlp(caesar)

stop=timeit.default_timer()
time=stop-start
print("time runing:",time)

time runing: 7.051385679


In [6]:
start=timeit.default_timer()

# Parse the cleaned novels. This can take a bit.
alice_doc = nlp(alice)

stop=timeit.default_timer()
time=stop-start
print("time runing:",time)

time runing: 8.851556287999998


In [7]:
start=timeit.default_timer()

# Group into sentences.
alice_sents = [[sent, "carroll"] for sent in alice_doc.sents]
caesar_sents = [[sent, "shakespeare"] for sent in caesar_doc.sents]

# Combine the sentences from the two novels into one data frame.
sentences = pd.DataFrame(alice_sents + caesar_sents)
sentences.head()

stop=timeit.default_timer()
time=stop-start
print("time runing:",time)

time runing: 0.009026945999998759


In [8]:
alice_sents

[[Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, 'and what is the use of a book,' thought Alice 'without pictures or conversation?',
  'carroll'],
 [So she was considering in her own mind (as well as she could, for the hot day made her feel very sleepy and stupid), whether the pleasure of making a daisy-chain would be worth the trouble of getting up and picking the daisies, when suddenly a White Rabbit with pink eyes ran close by her.,
  'carroll'],
 [There was nothing so VERY remarkable in that; nor did Alice think it so VERY much out of the way to hear the Rabbit say to itself, 'Oh dear!,
  'carroll'],
 [Oh dear!, 'carroll'],
 [I shall be late!', 'carroll'],
 [(when she thought it over afterwards, it occurred to her that she ought to have wondered at this, but at the time it all seemed quite natural); but when the 

In [9]:
sentences

0            1
0     (Alice, was, beginning, to, get, very, tired, ...      carroll
1     (So, she, was, considering, in, her, own, mind...      carroll
2     (There, was, nothing, so, VERY, remarkable, in...      carroll
3                                         (Oh, dear, !)      carroll
4                            (I, shall, be, late, !, ')      carroll
5     ((, when, she, thought, it, over, afterwards, ...      carroll
6     (In, another, moment, down, went, Alice, after...      carroll
7     (The, rabbit, -, hole, went, straight, on, lik...      carroll
8     (Either, the, well, was, very, deep, ,, or, sh...      carroll
9     (First, ,, she, tried, to, look, down, and, ma...      carroll
10    (and, there, she, saw, maps, and, pictures, hu...      carroll
11    (She, took, down, a, jar, from, one, of, the, ...      carroll
12    (Well, !, ', thought, Alice, to, herself, ,, '...      carroll
13    (How, brave, they, 'll, all, think, me, at, ho...      carroll
14    (Why, ,, I, would, n't, say, anything, about, ...      carroll
15            ((, Which, was, very, likely, true, ., ))      carroll
16                          (Down, ,, down, ,, down, .)      carroll
17    (Would, the, fall, NEVER, come, to, an, end, !...      carroll
18    (I, wonder, how, many, miles, I, 've, fallen, ...      carroll
19                             (she, said, aloud, ., ')      carroll
20    (I, must, be, getting, somewhere, near, the, c...      carroll
21    (Let, me, see, :, that, would, be, four, thous...      carroll
22      (yes, ,, that, 's, about, the, right, distance)      carroll
23    (but, then, I, wonder, what, Latitude, or, Lon...      carroll
24    ((, Alice, had, no, idea, what, Latitude, was,...      carroll
25                 (Presently, she, began, again, ., ')      carroll
26    (I, wonder, if, I, shall, fall, right, THROUGH...      carroll
27    (How, funny, it, 'll, seem, to, come, out, amo...      carroll
28    (The, Antipathies, ,, I, think, ', (, she, was...      carroll
29    (but, I, shall, have, to, ask, them, what, the...      carroll
...                                                 ...          ...
3783  (Enter, Antony, ,, Octauius, ,, Messala, ,, Lu...  shakespeare
3784                                          (Octa, .)  shakespeare
3785                           (What, man, is, that, ?)  shakespeare
3786                                         (Messa, .)  shakespeare
3787                              (My, Masters, man, .)  shakespeare
3788             (Strato, ,, where, is, thy, Master, ?)  shakespeare
3789                                          (Stra, .)  shakespeare
3790  (Free, from, the, Bondage, you, are, in, Messa...  shakespeare
3791  (For, Brutus, onely, ouercame, himselfe, ,, An...  shakespeare
3792                 (So, Brutus, should, be, found, .)  shakespeare
3793  (I, thank, thee, Brutus, That, thou, hast, pro...  shakespeare
3794  (All, that, seru'd, Brutus, ,, I, will, entert...  shakespeare
3795  (Fellow, ,, wilt, thou, bestow, thy, time, wit...  shakespeare
3796                                          (Stra, .)  shakespeare
3797  (I, ,, if, Messala, will, preferre, me, to, yo...  shakespeare
3798               (Do, so, ,, good, Messala, Messa, .)  shakespeare
3799                 (How, dyed, my, Master, Strato, ?)  shakespeare
3800                                          (Stra, .)  shakespeare
3801  (I, held, the, Sword, ,, and, he, did, run, on...  shakespeare
3802  (Octauius, ,, then, take, him, to, follow, the...  shakespeare
3803  (This, was, the, Noblest, Roman, of, them, all...  shakespeare
3804  (His, life, was, gentle, ,, and, the, Elements...  shakespeare
3805                    (;, This, was, a, man, Octa, .)  shakespeare
3806  (According, to, his, Vertue, ,, let, vs, vse, ...  shakespeare
3807  (Within, my, Tent, his, bones, to, night, shal...  shakespeare
3808  (So, call, the, Field, to, rest, ,, and, let, ...  shakespeare
3809                                        (Exeunt,

In [10]:
sentences[0].head()

0    (Alice, was, beginning, to, get, very, tired, ...
1    (So, she, was, considering, in, her, own, mind...
2    (There, was, nothing, so, VERY, remarkable, in...
3                                        (Oh, dear, !)
4                           (I, shall, be, late, !, ')
Name: 0, dtype: object

In [11]:
start=timeit.default_timer()

# Utility function to create a list of the 10 most common words.
def bag_of_words(text):
    
    # Filter out punctuation and stop words.
    allwords = [token.lemma_
                for token in text
                if not token.is_punct
                and not token.is_stop]
    
    # Return the most common words.
    return [item[0] for item in Counter(allwords).most_common(10)]
    

# Creates a data frame with features for each word in our common word set.
# Each value is the count of the times the word appears in each sentence.
def bow_features(sentences, common_words):
    
    # Scaffold the data frame and initialize counts to zero.
    df = pd.DataFrame(columns=common_words)
    df['text_sentence'] = sentences[0]
    df['text_source'] = sentences[1]
    df.loc[:, common_words] = 0
    
    # Process each row, counting the occurrence of words in each sentence.
    for i, sentence in enumerate(df['text_sentence']):
        
        # Convert the sentence to lemmas, then filter out punctuation,
        # stop words, and uncommon words.
        words = [token.lemma_
                 for token in sentence
                 if (
                     not token.is_punct
                     and not token.is_stop
                     and token.lemma_ in common_words
                 )]
        
        # Populate the row with word counts.
        for word in words:
            df.loc[i, word] += 1
        
        # This counter is just to make sure the kernel didn't hang.
        if i % 500 == 0:
            print("Processing row {}".format(i))
            
    return df

# Set up the bags.
alicewords = bag_of_words(alice_doc)
caesarwords = bag_of_words(caesar_doc)

# Combine bags to create a set of unique words.
common_words = set(alicewords + caesarwords)

stop=timeit.default_timer()
time=stop-start
print("time runing:",time)

time runing: 0.052745904000001786


In [12]:
start=timeit.default_timer()

# Create our data frame with features. This can take a while to run.
word_counts = bow_features(sentences, common_words)

stop=timeit.default_timer()
time=stop-start
print("time runing:",time)

Processing row 0
Processing row 500
Processing row 1000
Processing row 1500
Processing row 2000
Processing row 2500
Processing row 3000
Processing row 3500
time runing: 4.125869687999998


In [13]:
word_counts

little -PRON- say know shall go haue not caesar the     ...      alice  \
0         0      0   0    0     0  0    0   0      0   0     ...          2   
1         0      0   0    0     0  0    0   0      0   0     ...          0   
2         0      0   0    0     0  0    0   0      0   0     ...          1   
3         0      0   0    0     0  0    0   0      0   0     ...          0   
4         0      1   0    0     1  0    0   0      0   0     ...          0   
5         0      0   0    0     0  0    0   0      0   0     ...          1   
6         0      0   0    0     0  1    0   0      0   0     ...          1   
7         0      0   0    0     0  1    0   0      0   1     ...          1   
8         0      0   0    0     0  2    0   0      0   0     ...          0   
9         0      0   0    0     0  0    0   0      0   0     ...          0   
10        0      0   0    0     0  0    0   0      0   0     ...          0   
11        0      1   0    0     0  0    0   0      0   0     ...          0   
12        0      1   0    0     1  0    0   0      0   0     ...          1   
13        0      0   0    0     0  0    0   0      0   0     ...          0   
14        0      2   0    0     0  0    0   1      0   0     ...          0   
15        0      0   0    0     0  0    0   0      0   0     ...          0   
16        0      0   0    0     0  0    0   0      0   0     ...          0   
17        0      0   0    0     0  0    0   0      0   0     ...          0   
18        0      2   0    0     0  0    0   0      0   0     ...          0   
19        0      0   1    0     0  0    0   0      0   0     ...          0   
20        0      1   0    0     0  0    0   0      0   0     ...          0   
21        0      1   0    0     0  0    0   0      0   0     ...          1   
22        0      0   0    0     0  0    0   0      0   0     ...          0   
23        0      2   0    0     0  0    0   0      0   0     ...          0   
24        0      0   0    0     0  0    0   0      0   0     ...          1   
25        0      0   0    0     0  0    0   0      0   0     ...          0   
26        0      2   0    0     1  0    0   0      0   0     ...          0   
27        0      0   0    0     0  0    0   0      0   0     ...          0   
28        0      1   0    0     0  0    0   1      0   1     ...          0   
29        0      1   0    1     1  0    0   0      0   0     ...          0   
...     ...    ...  ..  ...   ... ..  ...  ..    ...  ..     ...        ...   
3783      0      0   0    0     0  0    0   0      0   0     ...          0   
3784      0      0   0    0     0  0    0   0      0   0     ...          0   
3785      0      0   0    0     0  0    0   0      0   0     ...          0   
3786      0      0   0    0     0  0    0   0      0   0     ...          0   
3787      0      1   0    0     0  0    0   0      0   0     ...          0   
3788      0      0   0    0     0  0    0   0      0   0     ...          0   
3789      0      0   0    0     0  0    0   0      0   0     ...          0   
3790      0      0   0    0     0  0    0   0      0   1     ...          0   
3791      0      0   0    0     0  0    0   0      0   0     ...          0   
3792      0      0   0    0     0  0    0   0      0   0     ...          0   
3793      0      1   1    0     0  0    0   0      0   0     ...          0   
3794      0      1   0    0     0  0    0   0      0   0     ...          0   
3795      0      0   0    0     0  0    0   0      0   0     ...          0   
3796      0      0   0    0     0  0    0   0      0   0     ...          0   
3797      0      1   0    0     0  0    0   0      0   0     ...          0   
3798      0      0   0    0     0  0    0   0      0   0     ...          0   
3799      0      0   0    0     0  0    0   0      0   0     ...          0   
3800      0      0   0    0     0  0    0   0      0   0     ...          0   
3801      0      1   0    0     0  0    0   0      0   

In [14]:
from sklearn import ensemble
from sklearn.model_selection import train_test_split

rfc = ensemble.RandomForestClassifier()
Y = word_counts['text_source']
X = np.array(word_counts.drop(['text_sentence','text_source'], 1))

In [15]:
print(Y)

0           carroll
1           carroll
2           carroll
3           carroll
4           carroll
5           carroll
6           carroll
7           carroll
8           carroll
9           carroll
10          carroll
11          carroll
12          carroll
13          carroll
14          carroll
15          carroll
16          carroll
17          carroll
18          carroll
19          carroll
20          carroll
21          carroll
22          carroll
23          carroll
24          carroll
25          carroll
26          carroll
27          carroll
28          carroll
29          carroll
           ...     
3783    shakespeare
3784    shakespeare
3785    shakespeare
3786    shakespeare
3787    shakespeare
3788    shakespeare
3789    shakespeare
3790    shakespeare
3791    shakespeare
3792    shakespeare
3793    shakespeare
3794    shakespeare
3795    shakespeare
3796    shakespeare
3797    shakespeare
3798    shakespeare
3799    shakespeare
3800    shakespeare
3801    shakespeare


In [16]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [17]:
Y.dtypes

dtype('O')

In [18]:
Y.shape

(3813,)

In [19]:
X.shape

(3813, 19)

In [20]:
start=timeit.default_timer()

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    Y,
                                                    test_size=0.4,
                                                    random_state=0)
train = rfc.fit(X_train, y_train)

print('Training set score:', rfc.score(X_train, y_train))
print('\nTest set score:', rfc.score(X_test, y_test))

stop=timeit.default_timer()
time=stop-start
print("time runing:",time)

c:\program files\python37\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Training set score: 0.829908176650634

Test set score: 0.8053735255570118
time runing: 0.059995997000001466


## BoW with Logistic Regression

In [21]:
start=timeit.default_timer()

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
train = lr.fit(X_train, y_train)
print(X_train.shape, y_train.shape)
print('Training set score:', lr.score(X_train, y_train))
print('\nTest set score:', lr.score(X_test, y_test))

print()
stop=timeit.default_timer()
time=stop-start
print("time runing:",time)

c:\program files\python37\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


(2287, 19) (2287,)
Training set score: 0.8224748578924355

Test set score: 0.8034076015727392

time runing: 0.05343952300000154


## BoW with Gradient Boosting

In [22]:
start=timeit.default_timer()

clf = ensemble.GradientBoostingClassifier()
train = clf.fit(X_train, y_train)

print('Training set score:', clf.score(X_train, y_train))
print('\nTest set score:', clf.score(X_test, y_test))

print()
stop=timeit.default_timer()
time=stop-start
print("time runing:",time)

Training set score: 0.8268473983384347

Test set score: 0.8066841415465269

time runing: 0.24090627900000072


In [23]:
import nltk
from nltk.corpus import gutenberg
nltk.download('gutenberg')
import re
from sklearn.model_selection import train_test_split

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\KH\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [24]:
#reading in the data, this time in the form of paragraphs
caesar=gutenberg.paras('shakespeare-caesar.txt')

#processing
caesar_paras=[]
for paragraph in caesar:
    para=paragraph[0]
    #removing the double-dash from all words
    para=[re.sub(r'--','',word) for word in para]
    #Forming each paragraph into a string and adding it to the list of strings.
    caesar_paras.append(' '.join(para))

print(caesar_paras[0:4])

['[ The Tragedie of Julius Caesar by William Shakespeare 1599 ]', 'Actus Primus .', 'Enter Flauius , Murellus , and certaine Commoners ouer the Stage .', 'Flauius .']


In [25]:
#reading in the data, this time in the form of paragraphs
alice=gutenberg.paras('carroll-alice.txt')

#processing
alice_paras=[]
for paragraph in caesar:
    para=paragraph[0]
    #removing the double-dash from all words
    para=[re.sub(r'--','',word) for word in para]
    #Forming each paragraph into a string and adding it to the list of strings.
    alice_paras.append(' '.join(para))

print(alice_paras[0:4])

['[ The Tragedie of Julius Caesar by William Shakespeare 1599 ]', 'Actus Primus .', 'Enter Flauius , Murellus , and certaine Commoners ouer the Stage .', 'Flauius .']


In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_df=0.5, 
                        # drop words that occur in more than half the paragraphs
                          
                         min_df=2, 
                         # only use words that appear at least twice
                             
                         stop_words='english', 
                             
                         lowercase=True, 
                             
                         #convert everything to lower case 
                         #(since Alice in Wonderland has the HABIT of CAPITALIZING WORDS 
                         # for EMPHASIS)
                             
                         use_idf=True,
                         #we definitely want to use inverse document frequencies in our weighting
                             
                         norm=u'l2', 
                         #Applies a correction factor so that longer paragraphs and 
                         #shorter paragraphs get treated equally
                             
                         smooth_idf=True 
                         #Adds 1 to all document frequencies, as if an extra document existed that used every word once.  Prevents divide-by-zero errors
                         )

In [27]:
#Applying the vectorizer
caesar_paras_tfidf=vectorizer.fit_transform(caesar_paras)
print("Number of features: %d" % caesar_paras_tfidf.get_shape()[1])

Number of features: 138


In [28]:
#Applying the vectorizer
alice_paras_tfidf=vectorizer.fit_transform(alice_paras)
print("Number of features: %d" % alice_paras_tfidf.get_shape()[1])

Number of features: 138


In [29]:
caesar_df=pd.DataFrame(caesar_paras_tfidf.toarray())

In [30]:
alice_df=pd.DataFrame(alice_paras_tfidf.toarray())

In [31]:
caesar_df.shape

(744, 138)

In [32]:
alice_df.shape

(744, 138)

In [33]:
caesar_df[138]='shakespeare'

In [34]:
alice_df[138]='carroll'

In [35]:
caesar_df.head(1)

0    1    2    3    4    5    6    7    8    9       ...       129  130  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     ...       0.0  0.0   

   131  132  133  134  135  136  137          138  
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  shakespeare  

[1 rows x 139 columns]

In [36]:
alice_df.head(1)

0    1    2    3    4    5    6    7    8    9     ...     129  130  131  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   ...     0.0  0.0  0.0   

   132  133  134  135  136  137      138  
0  0.0  0.0  0.0  0.0  0.0  0.0  carroll  

[1 rows x 139 columns]

In [37]:
df=pd.concat([caesar_df,alice_df],ignore_index=True)

In [38]:
df.shape

(1488, 139)

In [39]:
df.head()

0    1    2    3    4    5    6    7    8    9       ...       129  130  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     ...       0.0  0.0   
1  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     ...       0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     ...       0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     ...       0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     ...       0.0  0.0   

   131  132  133  134  135  136  137          138  
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  shakespeare  
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  shakespeare  
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  shakespeare  
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  shakespeare  
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  shakespeare  

[5 rows x 139 columns]

In [40]:
X=df.iloc[:,:138]

In [41]:
Y=df.iloc[:,138]

In [42]:
X.shape

(1488, 138)

In [43]:
Y.shape

(1488,)

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    Y,
                                                    test_size=0.4,
                                                    random_state=0)

In [45]:
lr = LogisticRegression()
train = lr.fit(X_train, y_train)
print(X_train.shape, y_train.shape)
print('Training set score:', lr.score(X_train, y_train))
print('\nTest set score:', lr.score(X_test, y_test))

c:\program files\python37\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


(892, 138) (892,)
Training set score: 0.5739910313901345

Test set score: 0.38926174496644295


In [46]:
clf = ensemble.GradientBoostingClassifier()
train = clf.fit(X_train, y_train)

print('Training set score:', clf.score(X_train, y_train))
print('\nTest set score:', clf.score(X_test, y_test))

Training set score: 0.5683856502242153

Test set score: 0.3976510067114094
